name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.1
          virtualenvs-create: false

      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Checkout Code
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.tag }}
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          source $HOME/.poetry/env
          poetry run poetry publish
